//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    using FTN;
    
    
    /// Pole-mounted fault interrupter with built-in phase and ground relays, current transformer (CT), and supplemental controls.
    public class Recloser : ProtectedSwitch {
    }
}
